// Compile a canonical multi-file MDX walkthrough into review UI data.
//
// Run with Bun:  bun run scripts/compile-walkthrough.ts [options]

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import {
  GuideCompileError,
  compareStrings,
  compileGuide,
  decodeGitMarkerPath,
  decodeGitMetadataPath,
  parseGitDiffHeader,
  removePrefix,
  rstripNewlines,
  splitGuideSection,
  splitLines,
  splitPatchBlocks,
  stripChars,
  type DiffFileSummary,
  type GuidePhase,
} from "./guide-contract";

const REVIEW_GUIDE_LABEL = "Review guide";
const LEGACY_LENS_HEADINGS = new Set([
  "System overview",
  "Data flow graph",
  "Code dependency graph",
  "User action graph",
]);
const REQUIRED_META = ["title", "baseRef", "headRef", "headSha", "summary"] as const;
const SUMMARY_MIN_WORDS = 8;
const SUMMARY_MAX_WORDS = 36;
const GENERIC_SUMMARY_PREFIXES = [
  "this group",
  "this change",
  "this pull request",
  "this pr",
  "the pr",
  "start with",
  "read ",
  "review ",
  "focus on",
];

const GENERATED_BASENAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "deno.lock",
  "cargo.lock",
  "go.sum",
  "composer.lock",
  "gemfile.lock",
  "podfile.lock",
  "pipfile.lock",
  "poetry.lock",
  "uv.lock",
  "packages.lock.json",
  "package.resolved",
  "packages-lock.json",
]);
const GENERATED_SUFFIXES: ReadonlyArray<readonly [string, string]> = [
  [".meta", "Unity asset metadata"],
  [".designer.cs", "Generated C# source"],
  [".generated.cs", "Generated C# source"],
  [".g.cs", "Generated C# source"],
  [".g.i.cs", "Generated C# source"],
  [".generated.ts", "Generated TypeScript source"],
  [".generated.tsx", "Generated TypeScript source"],
  [".generated.js", "Generated JavaScript source"],
  [".generated.jsx", "Generated JavaScript source"],
  [".pb.go", "Generated protocol source"],
  [".pb.cc", "Generated protocol source"],
  [".pb.h", "Generated protocol source"],
  ["_pb2.py", "Generated protocol source"],
  ["_pb2_grpc.py", "Generated protocol source"],
  [".grpc.go", "Generated protocol source"],
  [".min.js", "Minified artifact"],
  [".min.css", "Minified artifact"],
  [".js.map", "Source map"],
  [".css.map", "Source map"],
  [".snap", "Generated test snapshot"],
];
const GENERATED_PATH =
  /(?:^|\/)(?:generated|generated-sources|generated_sources|\.next|dist|coverage|obj)(?:\/|$)/i;
const GENERATED_HEADER =
  /^\s*(?:\/\/|#|\/\*|<!--|;|--)?\s*(?:<auto-generated\b|@generated\b|code generated .+ do not edit\b|this file (?:is|was) (?:auto(?:matically)?[- ]?)generated\b|generated by .+ do not edit\b)/im;

const FIRST_LEVEL_HEADING = /^# (.+?)\s*$/;
const SECOND_LEVEL_HEADING = /^## (.+?)\s*$/;
const SECTION_REFERENCE = /^- Section: \[([^\]]+)\]\(([^)]+\.mdx)\)\s*$/;
const LINK = /^\[([^\]]+)\]\(([^)]+)\)$/;
const COMMENT_DIRECTIVE = /^\*\*([^*]+)\*\* — (.+?)(?: \(\[Open\]\(([^)]+)\)\))?$/;
const INDEX_BLOBS = /^index ([0-9a-f]+)\.\.([0-9a-f]+)(?: \d+)?$/i;
const GROUP_ID = /^[a-z0-9][a-z0-9-]*$/;
const HEAD_SHA = /^[0-9a-fA-F]{40}$/;
const SUMMARY_WORD = /[A-Za-z0-9][A-Za-z0-9'’-]*/g;
const FULL_CONTEXT_MARKER_NAME = "full-context.enabled";
const MAX_EXPANDABLE_BLOB_BYTES = 2_000_000;
const MAX_EMBEDDED_CONTEXT_BYTES = 25_000_000;

/** Raised when the MDX authoring contract is invalid. */
export class CompileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CompileError";
  }
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

/** Resolve like Python's Path.resolve(): absolute, with symlinks followed. */
function resolveRealPath(target: string): string {
  const absolute = path.resolve(target);
  try {
    return fs.realpathSync(absolute);
  } catch {
    const parent = path.dirname(absolute);
    if (parent === absolute) return absolute;
    return path.join(resolveRealPath(parent), path.basename(absolute));
  }
}

function isFile(target: string): boolean {
  try {
    return fs.statSync(target).isFile();
  } catch {
    return false;
  }
}

function isDirectory(target: string): boolean {
  try {
    return fs.statSync(target).isDirectory();
  } catch {
    return false;
  }
}

function readTextFile(target: string): string {
  return new TextDecoder("utf-8", { fatal: true }).decode(fs.readFileSync(target));
}

/** Collect every *.mdx file below `root`, as paths relative to `root`. */
function collectMdxFiles(root: string): string[] {
  const found: string[] = [];
  const walk = (relative: string): void => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(path.join(root, relative), { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const next = relative ? `${relative}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(next);
      else if (entry.isFile() && entry.name.toLowerCase().endsWith(".mdx")) found.push(next);
    }
  };
  walk("");
  return found;
}

/** Order paths by their components, matching how Python sorted Path objects. */
function comparePaths(left: string, right: string): number {
  const leftParts = left.split("/");
  const rightParts = right.split("/");
  const limit = Math.min(leftParts.length, rightParts.length);
  for (let index = 0; index < limit; index += 1) {
    const result = compareStrings(leftParts[index], rightParts[index]);
    if (result !== 0) return result;
  }
  return leftParts.length - rightParts.length;
}

// ---------------------------------------------------------------------------
// Git access for optional full-context embedding
// ---------------------------------------------------------------------------

/** Resolve a repository root without invoking a shell. */
function findGitRoot(start: string): string | null {
  let candidate = resolveRealPath(start);
  if (isFile(candidate)) candidate = path.dirname(candidate);
  const result = spawnSync("git", ["-C", candidate, "rev-parse", "--show-toplevel"]);
  if (result.status !== 0 || !result.stdout) return null;
  let root: string;
  try {
    root = resolveRealPath(new TextDecoder("utf-8", { fatal: true }).decode(result.stdout).trim());
  } catch {
    return null;
  }
  return isDirectory(root) ? root : null;
}

/** Read a small UTF-8 Git blob addressed by a validated patch object ID. */
function readGitBlob(
  repoRoot: string,
  objectId: string,
  cache: Map<string, string | null>,
): string | null {
  const normalizedId = objectId.toLowerCase();
  const cached = cache.get(normalizedId);
  if (cached !== undefined || cache.has(normalizedId)) return cached ?? null;
  if (!normalizedId || /^0+$/.test(normalizedId)) {
    cache.set(normalizedId, null);
    return null;
  }

  const objectType = spawnSync("git", ["-C", repoRoot, "cat-file", "-t", normalizedId]);
  if (
    objectType.status !== 0 ||
    !objectType.stdout ||
    objectType.stdout.toString().trim() !== "blob"
  ) {
    cache.set(normalizedId, null);
    return null;
  }

  const sizeResult = spawnSync("git", ["-C", repoRoot, "cat-file", "-s", normalizedId]);
  const sizeText = sizeResult.stdout ? sizeResult.stdout.toString().trim() : "";
  if (!/^[+-]?[0-9]+$/.test(sizeText)) {
    cache.set(normalizedId, null);
    return null;
  }
  const size = Number(sizeText);
  if (sizeResult.status !== 0 || size > MAX_EXPANDABLE_BLOB_BYTES) {
    cache.set(normalizedId, null);
    return null;
  }

  const payloadResult = spawnSync("git", ["-C", repoRoot, "cat-file", "-p", normalizedId], {
    maxBuffer: MAX_EXPANDABLE_BLOB_BYTES + 1024,
  });
  const payload = payloadResult.stdout;
  if (
    payloadResult.status !== 0 ||
    !payload ||
    payload.length > MAX_EXPANDABLE_BLOB_BYTES ||
    payload.includes(0)
  ) {
    cache.set(normalizedId, null);
    return null;
  }
  let contents: string;
  try {
    contents = new TextDecoder("utf-8", { fatal: true }).decode(payload);
  } catch {
    cache.set(normalizedId, null);
    return null;
  }
  cache.set(normalizedId, contents);
  return contents;
}

// ---------------------------------------------------------------------------
// MDX parsing
// ---------------------------------------------------------------------------

/** Fail loudly instead of silently carrying removed diagram data forward. */
export function rejectLegacyLensSyntax(source: string, context: string): void {
  const lines = splitLines(source);
  for (let index = 0; index < lines.length; index += 1) {
    const lineNumber = index + 1;
    const rawLine = lines[index];
    if (rawLine.trim().startsWith("- Lens:")) {
      throw new CompileError(
        `${context}:${String(lineNumber)} uses the removed Lens syntax; ` +
          "delete the Lens entry and keep reviewer guidance in Section MDX files",
      );
    }
    const heading = FIRST_LEVEL_HEADING.exec(rawLine);
    if (heading && LEGACY_LENS_HEADINGS.has(heading[1])) {
      throw new CompileError(
        `${context}:${String(lineNumber)} uses the removed diagram heading ` +
          `'${heading[1]}'; delete that diagram and move any useful prose ` +
          "into the relevant review Section",
      );
    }
  }
}

/** Decode a quoted frontmatter scalar the way Python's literal_eval did. */
function parseQuotedScalar(text: string): string | null {
  const quote = text[0];
  if (quote !== "'" && quote !== '"') return null;
  if (text.length < 2 || text[text.length - 1] !== quote) return null;
  const body = text.slice(1, -1);
  let result = "";
  let index = 0;
  while (index < body.length) {
    const character = body[index];
    if (character === quote) return null;
    if (character !== "\\") {
      result += character;
      index += 1;
      continue;
    }
    index += 1;
    if (index >= body.length) return null;
    const escaped = body[index];
    index += 1;
    if (escaped === "\n") continue;
    const simple: Record<string, string> = {
      "\\": "\\",
      "'": "'",
      '"': '"',
      a: "\u0007",
      b: "\b",
      f: "\f",
      n: "\n",
      r: "\r",
      t: "\t",
      v: "\v",
    };
    if (Object.prototype.hasOwnProperty.call(simple, escaped)) {
      result += simple[escaped];
      continue;
    }
    if (escaped >= "0" && escaped <= "7") {
      const limit = Math.min(index + 2, body.length);
      let end = index;
      while (end < limit && body[end] >= "0" && body[end] <= "7") end += 1;
      result += String.fromCharCode(Number.parseInt(body.slice(index - 1, end), 8));
      index = end;
      continue;
    }
    if (escaped === "x" || escaped === "u" || escaped === "U") {
      const width = escaped === "x" ? 2 : escaped === "u" ? 4 : 8;
      const digits = body.slice(index, index + width);
      if (digits.length !== width || !/^[0-9a-fA-F]+$/.test(digits)) return null;
      const code = Number.parseInt(digits, 16);
      if (code > 0x10ffff) return null;
      result += String.fromCodePoint(code);
      index += width;
      continue;
    }
    result += `\\${escaped}`;
  }
  return result;
}

function scalar(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (trimmed.startsWith("'") || trimmed.startsWith('"')) {
    const parsed = parseQuotedScalar(trimmed);
    if (parsed !== null) return parsed;
  }
  return trimmed;
}

type Meta = Record<string, string>;

function parseFrontmatter(lines: string[]): [Meta, number] {
  if (lines.length === 0 || lines[0].trim() !== "---") {
    throw new CompileError("page.mdx must start with YAML frontmatter");
  }
  const meta: Meta = {};
  for (let offset = 1; offset < lines.length; offset += 1) {
    const index = offset;
    const line = lines[offset];
    if (line.trim() === "---") {
      const missing = REQUIRED_META.filter((key) => !meta[key]);
      if (missing.length > 0) {
        throw new CompileError(`frontmatter is missing: ${missing.join(", ")}`);
      }
      if (!HEAD_SHA.test(meta.headSha)) {
        throw new CompileError(
          "frontmatter headSha must be an explicit 40-character Git commit SHA",
        );
      }
      meta.headSha = meta.headSha.toLowerCase();
      if (meta.prUrl === undefined) meta.prUrl = "";
      return [meta, index + 1];
    }
    if (!line.trim() || line.replace(/^\s+/, "").startsWith("#")) continue;
    if (!line.includes(":")) {
      throw new CompileError(`invalid frontmatter line ${String(index + 1)}: ${line}`);
    }
    const separator = line.indexOf(":");
    meta[line.slice(0, separator).trim()] = scalar(line.slice(separator + 1));
  }
  throw new CompileError("frontmatter is missing its closing ---");
}

function readRelativeMdx(root: string, relativePath: string, context: string): string {
  const rootResolved = resolveRealPath(root);
  const candidate = resolveRealPath(path.resolve(rootResolved, relativePath));
  if (candidate !== rootResolved && !candidate.startsWith(`${rootResolved}${path.sep}`)) {
    throw new CompileError(`${context} must stay inside the walkthrough directory`);
  }
  if (path.extname(candidate).toLowerCase() !== ".mdx" || !isFile(candidate)) {
    throw new CompileError(`${context} does not exist: ${relativePath}`);
  }
  return readTextFile(candidate);
}

function parseSingleHeading(source: string, context: string): [string, string[]] {
  const lines = splitLines(source);
  const headings: Array<[number, string]> = [];
  for (let index = 0; index < lines.length; index += 1) {
    const match = FIRST_LEVEL_HEADING.exec(lines[index]);
    if (match) headings.push([index, match[1]]);
  }
  if (headings.length !== 1) {
    throw new CompileError(`${context} must contain exactly one first-level heading`);
  }
  const [index, title] = headings[0];
  return [title, lines.slice(index + 1)];
}

function paragraphs(lines: string[]): string[] {
  const result: string[] = [];
  let current: string[] = [];
  for (const rawLine of lines) {
    let line = rawLine.trim();
    if (!line) {
      if (current.length > 0) {
        result.push(current.join(" "));
        current = [];
      }
      continue;
    }
    if (line.startsWith("> ")) line = line.slice(2);
    else if (line.startsWith("- ")) line = line.slice(2);
    current.push(line);
  }
  if (current.length > 0) result.push(current.join(" "));
  return result;
}

function parseLink(value: string, context: string): [string, string] {
  const match = LINK.exec(value.trim());
  if (!match) throw new CompileError(`${context} must use [label](url) syntax`);
  return [match[1], stripChars(match[2], "<>")];
}

export interface GroupFile {
  path: string;
  url?: string;
  note?: string;
}

export interface GroupComment {
  author: string;
  body: string;
  url?: string;
}

export interface GroupLink {
  label: string;
  url: string;
}

export interface ReviewGroup {
  id: string;
  title: string;
  objective: string;
  summary: string;
  details: string[];
  files: GroupFile[];
  comments: GroupComment[];
  links: GroupLink[];
  guide?: { phases: GuidePhase[] };
}

function parseReviewGroup(title: string, lines: string[]): ReviewGroup {
  let groupId = "";
  let objective = "";
  const bodyLines: string[] = [];
  const files: GroupFile[] = [];
  const comments: GroupComment[] = [];
  const links: GroupLink[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    const afterColon = (): string => line.slice(line.indexOf(":") + 1).trim();
    if (line.startsWith("- Lens:")) {
      throw new CompileError(
        `review group ${groupId || title} uses the removed Lens directive; ` +
          "delete it and keep the review group focused on changed files and evidence",
      );
    }
    if (line.startsWith("- ID:")) {
      groupId = stripChars(afterColon(), "`");
      continue;
    }
    if (line.startsWith("- Objective:")) {
      objective = afterColon();
      continue;
    }
    if (line.startsWith("- File:")) {
      let value = afterColon();
      let note = "";
      const separator = value.indexOf(" — ");
      if (separator >= 0) {
        note = value.slice(separator + 3);
        value = value.slice(0, separator);
      }
      const [filePath, url] = parseLink(value, `file on review group ${groupId || title}`);
      const item: GroupFile = { path: filePath };
      if (url !== "-") item.url = url;
      if (note) item.note = note;
      files.push(item);
      continue;
    }
    if (line.startsWith("- Link:")) {
      const [label, url] = parseLink(afterColon(), `link on review group ${groupId || title}`);
      links.push({ label, url });
      continue;
    }
    if (line.startsWith("- Comment:")) {
      const value = afterColon();
      const match = COMMENT_DIRECTIVE.exec(value);
      if (!match) {
        throw new CompileError(
          `comment on review group ${groupId || title} must use **author** — body ([Open](url))`,
        );
      }
      const item: GroupComment = { author: match[1], body: match[2] };
      if (match[3]) item.url = stripChars(match[3], "<>");
      comments.push(item);
      continue;
    }
    bodyLines.push(rawLine);
  }

  if (!GROUP_ID.test(groupId)) {
    throw new CompileError(`review group ${title} needs a lowercase kebab-case ID directive`);
  }
  if (!objective) throw new CompileError(`review group ${groupId} needs an Objective directive`);
  const content = paragraphs(bodyLines);
  if (content.length === 0) {
    throw new CompileError(`review group ${groupId} needs explanatory Markdown`);
  }
  const summary = content[0];
  const summaryWords = summary.match(SUMMARY_WORD) ?? [];
  if (summaryWords.length < SUMMARY_MIN_WORDS || summaryWords.length > SUMMARY_MAX_WORDS) {
    throw new CompileError(`review group ${groupId} needs an 8–36 word concrete summary`);
  }
  const normalizedSummary = summary.toLowerCase();
  if (GENERIC_SUMMARY_PREFIXES.some((prefix) => normalizedSummary.startsWith(prefix))) {
    throw new CompileError(
      `review group ${groupId} summary must start with a subsystem or mechanism`,
    );
  }
  if (normalizedSummary === objective.trim().toLowerCase()) {
    throw new CompileError(`review group ${groupId} summary must add information beyond Objective`);
  }
  return {
    id: groupId,
    title,
    objective,
    summary,
    details: content.slice(1),
    files,
    comments,
    links,
  };
}

/** Parse Normal content unchanged and retain the required Guide source for compilation. */
function parseReviewGroupWithGuide(
  title: string,
  lines: string[],
  context: string,
): [ReviewGroup, string[]] {
  let split: [string[], string[]];
  try {
    split = splitGuideSection(lines, context);
  } catch (error) {
    if (error instanceof GuideCompileError) throw new CompileError(error.message);
    throw error;
  }
  return [parseReviewGroup(title, split[0]), split[1]];
}

function parseReviewGuide(lines: string[]): ReviewGroup[] {
  const groups: ReviewGroup[] = [];
  let current: [string, string[]] | null = null;
  for (const line of lines) {
    const heading = SECOND_LEVEL_HEADING.exec(line);
    if (heading) {
      if (current) groups.push(parseReviewGroup(current[0], current[1]));
      current = [heading[1], []];
    } else if (current) {
      current[1].push(line);
    }
  }
  if (current) groups.push(parseReviewGroup(current[0], current[1]));
  if (groups.length === 0) {
    throw new CompileError("Review guide needs at least one review group");
  }
  return groups;
}

function githubDiffUrl(prUrl: string, filePath: string): string {
  if (!prUrl || !filePath) return "";
  const digest = createHash("sha256").update(filePath, "utf8").digest("hex");
  return `${prUrl.replace(/\/+$/, "")}/files#diff-${digest}`;
}

export function classifyGeneratedFile(filePath: string, patch: string): [boolean, string] {
  const normalized = filePath.replace(/\\/g, "/").toLowerCase();
  const basename = normalized.slice(normalized.lastIndexOf("/") + 1);
  if (GENERATED_BASENAMES.has(basename)) return [true, "Dependency lockfile"];
  for (const [suffix, reason] of GENERATED_SUFFIXES) {
    if (normalized.endsWith(suffix)) return [true, reason];
  }
  if (GENERATED_PATH.test(normalized)) return [true, "Generated output directory"];
  const payload = splitLines(patch)
    .filter(
      (line) =>
        (line.startsWith(" ") || line.startsWith("+") || line.startsWith("-")) &&
        !line.startsWith("+++") &&
        !line.startsWith("---"),
    )
    .map((line) => line.slice(1))
    .join("\n");
  if (GENERATED_HEADER.test(payload)) return [true, "Generated source marker"];
  return [false, ""];
}

export interface DiffFile extends DiffFileSummary {
  path: string;
  status: string;
  additions: number;
  deletions: number;
  patch: string;
  binary: boolean;
  generated: boolean;
  url: string;
  generatedReason?: string;
  previousPath?: string;
  oldContents?: string;
  newContents?: string;
}

export function parsePatch(
  patch: string,
  prUrl: string,
  repoRoot: string | null = null,
): DiffFile[] {
  const files: DiffFile[] = [];
  const blobCache = new Map<string, string | null>();
  let embeddedContextBytes = 0;
  const encoder = new TextEncoder();
  for (const block of splitPatchBlocks(patch)) {
    if (!block.startsWith("diff --git ")) continue;
    const lines = rstripNewlines(block).split("\n");
    const header = parseGitDiffHeader(lines[0]);
    let oldPath = header[0];
    let newPath = header[1];
    let renameFrom = "";
    let renameTo = "";
    let copiedFrom = "";
    let copiedTo = "";
    let oldBlob = "";
    let newBlob = "";
    let status = "modified";
    let firstHunk = lines.length;
    for (let index = 0; index < lines.length; index += 1) {
      if (lines[index].startsWith("@@ ")) {
        firstHunk = index;
        break;
      }
    }
    for (const line of lines.slice(1, firstHunk)) {
      if (line.startsWith("new file mode ")) status = "added";
      else if (line.startsWith("deleted file mode ")) status = "deleted";
      else if (line.startsWith("--- ")) oldPath = decodeGitMarkerPath(removePrefix(line, "--- "));
      else if (line.startsWith("+++ ")) newPath = decodeGitMarkerPath(removePrefix(line, "+++ "));
      else if (line.startsWith("rename from ")) {
        renameFrom = decodeGitMetadataPath(removePrefix(line, "rename from "));
        status = "renamed";
      } else if (line.startsWith("rename to ")) {
        renameTo = decodeGitMetadataPath(removePrefix(line, "rename to "));
        status = "renamed";
      } else if (line.startsWith("copy from ")) {
        copiedFrom = decodeGitMetadataPath(removePrefix(line, "copy from "));
        status = "copied";
      } else if (line.startsWith("copy to ")) {
        copiedTo = decodeGitMetadataPath(removePrefix(line, "copy to "));
        status = "copied";
      } else {
        const match = INDEX_BLOBS.exec(line);
        if (match) {
          oldBlob = match[1];
          newBlob = match[2];
        }
      }
    }

    const filePath = renameTo || copiedTo || (status === "deleted" ? oldPath : newPath);
    if (!filePath) continue;
    let additions = 0;
    let deletions = 0;
    for (const line of lines.slice(firstHunk + 1)) {
      if (line.startsWith("+")) additions += 1;
      if (line.startsWith("-")) deletions += 1;
    }
    const [generated, generatedReason] = classifyGeneratedFile(filePath, block);
    const item: DiffFile = {
      path: filePath,
      status,
      additions,
      deletions,
      patch: `${rstripNewlines(block)}\n`,
      binary: block.includes("GIT binary patch") || block.includes("Binary files "),
      generated,
      url: githubDiffUrl(prUrl, filePath),
    };
    if (generatedReason) item.generatedReason = generatedReason;
    const previousPath = renameFrom || copiedFrom || (oldPath !== filePath ? oldPath : "");
    if (previousPath) item.previousPath = previousPath;
    if (
      repoRoot !== null &&
      !item.binary &&
      (status === "modified" || status === "renamed" || status === "copied") &&
      oldBlob &&
      newBlob
    ) {
      const oldContents = readGitBlob(repoRoot, oldBlob, blobCache);
      const newContents = readGitBlob(repoRoot, newBlob, blobCache);
      if (oldContents !== null && newContents !== null) {
        const contextBytes =
          encoder.encode(oldContents).length + encoder.encode(newContents).length;
        if (embeddedContextBytes + contextBytes <= MAX_EMBEDDED_CONTEXT_BYTES) {
          item.oldContents = oldContents;
          item.newContents = newContents;
          embeddedContextBytes += contextBytes;
        }
      }
    }
    files.push(item);
  }
  return files;
}

function fallbackReviewGroups(meta: Meta, diffFiles: DiffFile[]): ReviewGroup[] {
  return [
    {
      id: "review-path",
      title: "Review path",
      objective: meta.summary,
      summary: meta.summary,
      details: [],
      files: diffFiles.map((file) => ({
        path: file.path,
        url: file.url,
        note: "Changed file in this pull request.",
      })),
      comments: [],
      links: [],
    },
  ];
}

function validateReviewGroups(
  groups: ReviewGroup[],
  diffFiles: DiffFile[],
  requireFileCoverage: boolean,
): void {
  const diffByPath = new Map<string, DiffFile>();
  for (const file of diffFiles) diffByPath.set(file.path, file);
  const groupIds = groups.map((group) => group.id);
  if (new Set(groupIds).size !== groupIds.length) {
    throw new CompileError("Review guide has duplicate group IDs");
  }

  const referencedFiles: string[] = [];
  for (const group of groups) {
    const groupFilePaths = group.files.map((file) => file.path);
    if (new Set(groupFilePaths).size !== groupFilePaths.length) {
      throw new CompileError(`review group ${group.id} repeats a changed file`);
    }
    for (const file of group.files) {
      const diffFile = diffByPath.get(file.path);
      if (!diffFile) {
        throw new CompileError(
          `review group ${group.id} references a file missing from the patch: ${file.path}`,
        );
      }
      if (file.url === undefined) file.url = diffFile.url;
      referencedFiles.push(file.path);
    }
  }

  if (requireFileCoverage && diffFiles.length > 0) {
    const counts = new Map<string, number>();
    for (const filePath of referencedFiles) {
      counts.set(filePath, (counts.get(filePath) ?? 0) + 1);
    }
    const duplicateFiles = [...counts.entries()]
      .filter(([, count]) => count > 1)
      .map(([filePath]) => filePath)
      .toSorted(compareStrings);
    if (duplicateFiles.length > 0) {
      throw new CompileError(
        `Review guide assigns changed files to more than one group: ${duplicateFiles.join(", ")}`,
      );
    }
    const referenced = new Set(referencedFiles);
    const missingFiles = [...diffByPath.keys()]
      .filter((filePath) => !referenced.has(filePath))
      .toSorted(compareStrings);
    if (missingFiles.length > 0) {
      throw new CompileError(
        `Review guide does not assign every changed file: ${missingFiles.join(", ")}`,
      );
    }
  }
}

export interface WalkthroughData {
  meta: {
    title: string;
    prUrl: string;
    baseRef: string;
    headRef: string;
    headSha: string;
    summary: string;
  };
  reviewGroups: ReviewGroup[];
  diffFiles: DiffFile[];
}

function buildMeta(meta: Meta): WalkthroughData["meta"] {
  return {
    title: meta.title,
    prUrl: meta.prUrl,
    baseRef: meta.baseRef,
    headRef: meta.headRef,
    headSha: meta.headSha,
    summary: meta.summary,
  };
}

export function compileWalkthroughDir(
  root: string,
  patch = "",
  repoRoot: string | null = null,
): WalkthroughData {
  const manifestPath = path.join(root, "index.mdx");
  if (!isFile(manifestPath)) {
    throw new CompileError("walkthrough directory must contain index.mdx");
  }

  for (const relative of collectMdxFiles(root).toSorted(comparePaths)) {
    rejectLegacyLensSyntax(readTextFile(path.join(root, relative)), relative);
  }

  const lines = splitLines(readTextFile(manifestPath));
  const [meta, bodyStart] = parseFrontmatter(lines);
  const body = lines.slice(bodyStart);
  if (!body.some((line) => line.trim() === "# Review guide")) {
    throw new CompileError("index.mdx must contain # Review guide");
  }

  const references: Array<[string, string]> = [];
  for (const line of body) {
    if (!line.trim()) continue;
    const match = SECTION_REFERENCE.exec(line.trim());
    if (match) references.push([match[1], match[2]]);
  }
  if (references.length === 0) {
    throw new CompileError("index.mdx must reference at least one Section MDX file");
  }
  const paths = references.map(([, value]) => value);
  if (new Set(paths).size !== paths.length) {
    throw new CompileError("index.mdx repeats an MDX file reference");
  }

  const reviewGroups: ReviewGroup[] = [];
  const guideSources: string[][] = [];
  for (const [label, relativePath] of references) {
    const source = readRelativeMdx(root, relativePath, `Section ${label}`);
    const [title, sectionLines] = parseSingleHeading(source, `Section ${relativePath}`);
    if (title !== label) {
      throw new CompileError(`Section label ${label} must match its heading ${title}`);
    }
    const [group, guideLines] = parseReviewGroupWithGuide(
      title,
      sectionLines,
      `Section ${relativePath}`,
    );
    reviewGroups.push(group);
    guideSources.push(guideLines);
  }

  const diffFiles = parsePatch(patch, meta.prUrl, repoRoot);
  validateReviewGroups(reviewGroups, diffFiles, true);
  for (let index = 0; index < reviewGroups.length; index += 1) {
    const group = reviewGroups[index];
    try {
      group.guide = compileGuide(guideSources[index], {
        groupId: group.id,
        groupPaths: new Set(group.files.map((file) => file.path)),
        diffFiles,
        patch,
      });
    } catch (error) {
      if (error instanceof GuideCompileError) throw new CompileError(error.message);
      throw error;
    }
  }
  return { meta: buildMeta(meta), reviewGroups, diffFiles };
}

export function compileMdx(
  source: string,
  patch = "",
  repoRoot: string | null = null,
): WalkthroughData {
  rejectLegacyLensSyntax(source, "page.mdx");
  const lines = splitLines(source);
  const [meta, bodyStart] = parseFrontmatter(lines);
  const requiredMarkers = [
    "import { WalkthroughApp }",
    "import { WalkthroughSource }",
    "<WalkthroughApp",
    "<WalkthroughSource>",
    "</WalkthroughSource>",
  ];
  const missingMarkers = requiredMarkers.filter((marker) => !source.includes(marker));
  if (missingMarkers.length > 0) {
    throw new CompileError(
      "page.mdx must import and render WalkthroughApp and wrap its source in WalkthroughSource; " +
        `missing ${missingMarkers.join(", ")}`,
    );
  }

  const sections = new Map<string, string[]>();
  let currentLabel: string | null = null;
  for (const line of lines.slice(bodyStart)) {
    if (line.trim() === "</WalkthroughSource>") {
      currentLabel = null;
      continue;
    }
    const heading = FIRST_LEVEL_HEADING.exec(line);
    if (heading) {
      const label = heading[1];
      if (label === REVIEW_GUIDE_LABEL) {
        if (sections.has(label)) {
          throw new CompileError(`page.mdx repeats the ${label} heading`);
        }
        currentLabel = label;
        sections.set(currentLabel, []);
      } else {
        currentLabel = null;
      }
      continue;
    }
    if (currentLabel) (sections.get(currentLabel) as string[]).push(line);
  }

  const diffFiles = parsePatch(patch, meta.prUrl, repoRoot);
  const authoredReviewGuide = sections.has(REVIEW_GUIDE_LABEL);
  const reviewGroups = authoredReviewGuide
    ? parseReviewGuide(sections.get(REVIEW_GUIDE_LABEL) as string[])
    : fallbackReviewGroups(meta, diffFiles);
  validateReviewGroups(reviewGroups, diffFiles, authoredReviewGuide);
  return { meta: buildMeta(meta), reviewGroups, diffFiles };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const USAGE = `usage: compile-walkthrough.ts [-h] [--input INPUT] [--output OUTPUT] [--diff DIFF]
                              [--include-full-context] [--repo REPO]

Compile a canonical multi-file MDX walkthrough into review UI data.
`;

function usageError(message: string): never {
  process.stderr.write(USAGE);
  process.stderr.write(`compile-walkthrough.ts: error: ${message}\n`);
  process.exit(2);
}

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

function parseCliArgs(
  argv: string[],
  optionNames: string[],
  flagNames: string[],
): { values: Map<string, string>; flags: Set<string> } {
  const values = new Map<string, string>();
  const flags = new Set<string>();
  let index = 0;
  while (index < argv.length) {
    const token = argv[index];
    if (token === "-h" || token === "--help") {
      process.stdout.write(USAGE);
      process.exit(0);
    }
    const equals = token.indexOf("=");
    const name = equals >= 0 ? token.slice(0, equals) : token;
    if (equals < 0 && flagNames.includes(name)) {
      flags.add(name);
      index += 1;
      continue;
    }
    if (optionNames.includes(name)) {
      if (equals >= 0) {
        values.set(name, token.slice(equals + 1));
        index += 1;
        continue;
      }
      const value: string | undefined = argv[index + 1];
      if (value === undefined) usageError(`argument ${name}: expected one argument`);
      values.set(name, value);
      index += 2;
      continue;
    }
    usageError(`unrecognized arguments: ${token}`);
  }
  return { values, flags };
}

/** Escape non-ASCII the way Python's json.dumps did, so output stays byte-stable. */
function ensureAscii(value: string): string {
  return value.replace(
    /[\u0080-\uffff]/g,
    (character) => `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );
}

function isSystemError(error: unknown): boolean {
  return error instanceof Error && typeof (error as NodeJS.ErrnoException).code === "string";
}

function main(argv: string[]): number {
  const parsed = parseCliArgs(
    argv,
    ["--input", "--output", "--diff", "--repo"],
    ["--include-full-context"],
  );
  const inputPath = parsed.values.get("--input") ?? "src/content/walkthrough";
  const outputPath = parsed.values.get("--output") ?? "src/data/walkthrough.generated.json";
  const diffPath = parsed.values.get("--diff") ?? "src/data/walkthrough.patch";
  const repoArg = parsed.values.get("--repo");

  let data: WalkthroughData;
  try {
    const patch = isFile(diffPath) ? readTextFile(diffPath) : "";
    const siteRoot = path.dirname(path.dirname(resolveRealPath(fileURLToPath(import.meta.url))));
    const markerPath = path.join(siteRoot, "src", "data", FULL_CONTEXT_MARKER_NAME);
    const includeFullContext = parsed.flags.has("--include-full-context") || isFile(markerPath);
    let repoRoot: string | null = null;
    if (includeFullContext) {
      repoRoot = findGitRoot(repoArg ?? process.cwd());
      if (repoRoot === null) {
        throw new CompileError(
          "full context was requested, but no Git repository could be resolved",
        );
      }
    }
    data = isDirectory(inputPath)
      ? compileWalkthroughDir(inputPath, patch, repoRoot)
      : compileMdx(readTextFile(inputPath), patch, repoRoot);
  } catch (error) {
    if (error instanceof CompileError || isSystemError(error)) {
      fail(`walkthrough compile failed: ${(error as Error).message}`);
    }
    throw error;
  }

  fs.mkdirSync(path.dirname(path.resolve(outputPath)), { recursive: true });
  fs.writeFileSync(outputPath, `${ensureAscii(JSON.stringify(data, null, 2))}\n`, "utf8");
  process.stdout.write(`${outputPath}\n`);
  return 0;
}

const invokedAs = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (invokedAs === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
