#!/usr/bin/env python3
"""Compile a canonical multi-file MDX walkthrough into review UI data."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import shlex
import subprocess
from pathlib import Path

from guide_contract import GuideCompileError, compile_guide, split_guide_section

REVIEW_GUIDE_LABEL = "Review guide"
LEGACY_LENS_HEADINGS = {
    "System overview",
    "Data flow graph",
    "Code dependency graph",
    "User action graph",
}
REQUIRED_META = ("title", "baseRef", "headRef", "headSha", "summary")
SUMMARY_MIN_WORDS = 8
SUMMARY_MAX_WORDS = 36
GENERIC_SUMMARY_PREFIXES = (
    "this group",
    "this change",
    "this pull request",
    "this pr",
    "the pr",
    "start with",
    "read ",
    "review ",
    "focus on",
)

GENERATED_BASENAMES = {
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "deno.lock",
    "cargo.lock",
    "go.sum",
    "composer.lock",
    "gemfile.lock",
    "podfile.lock",
    "pipfile.lock",
    "poetry.lock",
    "uv.lock",
    "packages.lock.json",
    "package.resolved",
    "packages-lock.json",
}
GENERATED_SUFFIXES = (
    (".meta", "Unity asset metadata"),
    (".designer.cs", "Generated C# source"),
    (".generated.cs", "Generated C# source"),
    (".g.cs", "Generated C# source"),
    (".g.i.cs", "Generated C# source"),
    (".generated.ts", "Generated TypeScript source"),
    (".generated.tsx", "Generated TypeScript source"),
    (".generated.js", "Generated JavaScript source"),
    (".generated.jsx", "Generated JavaScript source"),
    (".pb.go", "Generated protocol source"),
    (".pb.cc", "Generated protocol source"),
    (".pb.h", "Generated protocol source"),
    ("_pb2.py", "Generated protocol source"),
    ("_pb2_grpc.py", "Generated protocol source"),
    (".grpc.go", "Generated protocol source"),
    (".min.js", "Minified artifact"),
    (".min.css", "Minified artifact"),
    (".js.map", "Source map"),
    (".css.map", "Source map"),
    (".snap", "Generated test snapshot"),
)
GENERATED_PATH = re.compile(
    r"(?:^|/)(?:generated|generated-sources|generated_sources|\.next|dist|coverage|obj)(?:/|$)",
    re.IGNORECASE,
)
GENERATED_HEADER = re.compile(
    r"(?im)^\s*(?://|#|/\*|<!--|;|--)?\s*(?:"
    r"<auto-generated\b|@generated\b|"
    r"code generated .+ do not edit\b|"
    r"this file (?:is|was) (?:auto(?:matically)?[- ]?)generated\b|"
    r"generated by .+ do not edit\b)",
)

FIRST_LEVEL_HEADING = re.compile(r"^# (.+?)\s*$")
SECOND_LEVEL_HEADING = re.compile(r"^## (.+?)\s*$")
SECTION_REFERENCE = re.compile(r"^- Section: \[([^]]+)]\(([^)]+\.mdx)\)\s*$")
LINK = re.compile(r"^\[([^]]+)]\(([^)]+)\)$")
INDEX_BLOBS = re.compile(
    r"^index ([0-9a-f]+)\.\.([0-9a-f]+)(?: \d+)?$",
    re.IGNORECASE,
)
FULL_CONTEXT_MARKER_NAME = "full-context.enabled"
MAX_EXPANDABLE_BLOB_BYTES = 2_000_000
MAX_EMBEDDED_CONTEXT_BYTES = 25_000_000


class CompileError(ValueError):
    """Raised when the MDX authoring contract is invalid."""


def find_git_root(start: Path) -> Path | None:
    """Resolve a repository root without invoking a shell."""

    candidate = start.resolve()
    if candidate.is_file():
        candidate = candidate.parent
    result = subprocess.run(
        ["git", "-C", str(candidate), "rev-parse", "--show-toplevel"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        return None
    try:
        root = Path(result.stdout.decode("utf-8").strip()).resolve()
    except UnicodeDecodeError:
        return None
    return root if root.is_dir() else None


def read_git_blob(
    repo_root: Path,
    object_id: str,
    cache: dict[str, str | None],
) -> str | None:
    """Read a small UTF-8 Git blob addressed by a validated patch object ID."""

    normalized_id = object_id.lower()
    if normalized_id in cache:
        return cache[normalized_id]
    if not normalized_id or set(normalized_id) == {"0"}:
        cache[normalized_id] = None
        return None

    object_type = subprocess.run(
        ["git", "-C", str(repo_root), "cat-file", "-t", normalized_id],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if object_type.returncode != 0 or object_type.stdout.strip() != b"blob":
        cache[normalized_id] = None
        return None

    size_result = subprocess.run(
        ["git", "-C", str(repo_root), "cat-file", "-s", normalized_id],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        size = int(size_result.stdout.strip())
    except (TypeError, ValueError):
        cache[normalized_id] = None
        return None
    if size_result.returncode != 0 or size > MAX_EXPANDABLE_BLOB_BYTES:
        cache[normalized_id] = None
        return None

    payload_result = subprocess.run(
        ["git", "-C", str(repo_root), "cat-file", "-p", normalized_id],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    payload = payload_result.stdout
    if (
        payload_result.returncode != 0
        or len(payload) > MAX_EXPANDABLE_BLOB_BYTES
        or b"\0" in payload
    ):
        cache[normalized_id] = None
        return None
    try:
        contents = payload.decode("utf-8")
    except UnicodeDecodeError:
        cache[normalized_id] = None
        return None
    cache[normalized_id] = contents
    return contents


def reject_legacy_lens_syntax(source: str, context: str) -> None:
    """Fail loudly instead of silently carrying removed diagram data forward."""

    for line_number, raw_line in enumerate(source.splitlines(), start=1):
        line = raw_line.strip()
        if line.startswith("- Lens:"):
            raise CompileError(
                f"{context}:{line_number} uses the removed Lens syntax; "
                "delete the Lens entry and keep reviewer guidance in Section MDX files"
            )
        heading = FIRST_LEVEL_HEADING.match(raw_line)
        if heading and heading.group(1) in LEGACY_LENS_HEADINGS:
            raise CompileError(
                f"{context}:{line_number} uses the removed diagram heading "
                f"{heading.group(1)!r}; delete that diagram and move any useful prose "
                "into the relevant review Section"
            )


def scalar(value: str) -> str:
    value = value.strip()
    if not value:
        return ""
    if value[:1] in {"'", '"'}:
        try:
            parsed = ast.literal_eval(value)
            return str(parsed)
        except (SyntaxError, ValueError):
            pass
    return value


def parse_frontmatter(lines: list[str]) -> tuple[dict[str, str], int]:
    if not lines or lines[0].strip() != "---":
        raise CompileError("page.mdx must start with YAML frontmatter")
    meta: dict[str, str] = {}
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            missing = [key for key in REQUIRED_META if not meta.get(key)]
            if missing:
                raise CompileError("frontmatter is missing: " + ", ".join(missing))
            if not re.fullmatch(r"[0-9a-fA-F]{40}", meta["headSha"]):
                raise CompileError("frontmatter headSha must be an explicit 40-character Git commit SHA")
            meta["headSha"] = meta["headSha"].lower()
            meta.setdefault("prUrl", "")
            return meta, index + 1
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise CompileError(f"invalid frontmatter line {index + 1}: {line}")
        key, value = line.split(":", 1)
        meta[key.strip()] = scalar(value)
    raise CompileError("frontmatter is missing its closing ---")


def read_relative_mdx(root: Path, relative_path: str, context: str) -> str:
    candidate = (root / relative_path).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError as error:
        raise CompileError(f"{context} must stay inside the walkthrough directory") from error
    if candidate.suffix.lower() != ".mdx" or not candidate.is_file():
        raise CompileError(f"{context} does not exist: {relative_path}")
    return candidate.read_text(encoding="utf-8")


def parse_single_heading(source: str, context: str) -> tuple[str, list[str]]:
    lines = source.splitlines()
    headings = [
        (index, match.group(1))
        for index, line in enumerate(lines)
        if (match := FIRST_LEVEL_HEADING.match(line))
    ]
    if len(headings) != 1:
        raise CompileError(f"{context} must contain exactly one first-level heading")
    index, title = headings[0]
    return title, lines[index + 1 :]


def paragraphs(lines: list[str]) -> list[str]:
    result: list[str] = []
    current: list[str] = []
    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            if current:
                result.append(" ".join(current))
                current = []
            continue
        if line.startswith("> "):
            line = line[2:]
        elif line.startswith("- "):
            line = line[2:]
        current.append(line)
    if current:
        result.append(" ".join(current))
    return result


def parse_link(value: str, context: str) -> tuple[str, str]:
    match = LINK.match(value.strip())
    if not match:
        raise CompileError(f"{context} must use [label](url) syntax")
    return match.group(1), match.group(2).strip("<>")


def parse_review_group(title: str, lines: list[str]) -> dict:
    group_id = ""
    objective = ""
    body_lines: list[str] = []
    files: list[dict[str, str]] = []
    comments: list[dict[str, str]] = []
    links: list[dict[str, str]] = []

    for raw_line in lines:
        line = raw_line.strip()
        if line.startswith("- Lens:"):
            raise CompileError(
                f"review group {group_id or title} uses the removed Lens directive; "
                "delete it and keep the review group focused on changed files and evidence"
            )
        if line.startswith("- ID:"):
            group_id = line.split(":", 1)[1].strip().strip("`")
            continue
        if line.startswith("- Objective:"):
            objective = line.split(":", 1)[1].strip()
            continue
        if line.startswith("- File:"):
            value = line.split(":", 1)[1].strip()
            note = ""
            if " — " in value:
                value, note = value.split(" — ", 1)
            path, url = parse_link(value, f"file on review group {group_id or title}")
            item = {"path": path}
            if url != "-":
                item["url"] = url
            if note:
                item["note"] = note
            files.append(item)
            continue
        if line.startswith("- Link:"):
            label, url = parse_link(line.split(":", 1)[1].strip(), f"link on review group {group_id or title}")
            links.append({"label": label, "url": url})
            continue
        if line.startswith("- Comment:"):
            value = line.split(":", 1)[1].strip()
            match = re.match(r"^\*\*([^*]+)\*\* — (.+?)(?: \(\[Open]\(([^)]+)\)\))?$", value)
            if not match:
                raise CompileError(
                    f"comment on review group {group_id or title} must use **author** — body ([Open](url))"
                )
            item = {"author": match.group(1), "body": match.group(2)}
            if match.group(3):
                item["url"] = match.group(3).strip("<>")
            comments.append(item)
            continue
        body_lines.append(raw_line)

    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", group_id):
        raise CompileError(f"review group {title} needs a lowercase kebab-case ID directive")
    if not objective:
        raise CompileError(f"review group {group_id} needs an Objective directive")
    content = paragraphs(body_lines)
    if not content:
        raise CompileError(f"review group {group_id} needs explanatory Markdown")
    summary = content[0]
    summary_words = re.findall(r"[A-Za-z0-9][A-Za-z0-9'’-]*", summary)
    if not SUMMARY_MIN_WORDS <= len(summary_words) <= SUMMARY_MAX_WORDS:
        raise CompileError(f"review group {group_id} needs an 8–36 word concrete summary")
    normalized_summary = summary.casefold()
    if normalized_summary.startswith(GENERIC_SUMMARY_PREFIXES):
        raise CompileError(f"review group {group_id} summary must start with a subsystem or mechanism")
    if normalized_summary == objective.strip().casefold():
        raise CompileError(f"review group {group_id} summary must add information beyond Objective")
    return {
        "id": group_id,
        "title": title,
        "objective": objective,
        "summary": summary,
        "details": content[1:],
        "files": files,
        "comments": comments,
        "links": links,
    }


def parse_review_group_with_guide(title: str, lines: list[str], context: str) -> dict:
    """Parse Normal content unchanged and retain the required Guide source for compilation."""

    try:
        normal_lines, guide_lines = split_guide_section(lines, context)
    except GuideCompileError as error:
        raise CompileError(str(error)) from error
    group = parse_review_group(title, normal_lines)
    group["_guideLines"] = guide_lines
    return group


def parse_review_guide(lines: list[str]) -> list[dict]:
    groups: list[dict] = []
    current_group: tuple[str, list[str]] | None = None

    def finish_group() -> None:
        nonlocal current_group
        if current_group:
            title, group_lines = current_group
            groups.append(parse_review_group(title, group_lines))
            current_group = None

    for line in lines:
        heading = SECOND_LEVEL_HEADING.match(line)
        if heading:
            finish_group()
            current_group = (heading.group(1), [])
        elif current_group:
            current_group[1].append(line)

    finish_group()
    if not groups:
        raise CompileError("Review guide needs at least one review group")
    return groups


def strip_git_prefix(path: str) -> str:
    return path[2:] if path.startswith(("a/", "b/")) else path


def parse_diff_header(line: str) -> tuple[str, str]:
    try:
        fields = shlex.split(line)
    except ValueError:
        fields = line.split()
    if len(fields) < 4:
        return "", ""
    return strip_git_prefix(fields[2]), strip_git_prefix(fields[3])


def github_diff_url(pr_url: str, path: str) -> str:
    if not pr_url or not path:
        return ""
    digest = hashlib.sha256(path.encode("utf-8")).hexdigest()
    return f"{pr_url.rstrip('/')}/files#diff-{digest}"


def classify_generated_file(path: str, patch: str) -> tuple[bool, str]:
    normalized = path.replace("\\", "/").lower()
    basename = normalized.rsplit("/", 1)[-1]
    if basename in GENERATED_BASENAMES:
        return True, "Dependency lockfile"
    for suffix, reason in GENERATED_SUFFIXES:
        if normalized.endswith(suffix):
            return True, reason
    if GENERATED_PATH.search(normalized):
        return True, "Generated output directory"
    payload = "\n".join(
        line[1:]
        for line in patch.splitlines()
        if line[:1] in {" ", "+", "-"} and not line.startswith(("+++", "---"))
    )
    if GENERATED_HEADER.search(payload):
        return True, "Generated source marker"
    return False, ""


def parse_patch(
    patch: str,
    pr_url: str,
    repo_root: Path | None = None,
) -> list[dict]:
    blocks = re.split(r"(?=^diff --git )", patch, flags=re.MULTILINE)
    files: list[dict] = []
    blob_cache: dict[str, str | None] = {}
    embedded_context_bytes = 0
    for block in blocks:
        if not block.startswith("diff --git "):
            continue
        lines = block.rstrip("\n").splitlines()
        old_path, new_path = parse_diff_header(lines[0])
        rename_from = ""
        rename_to = ""
        copied_to = ""
        old_blob = ""
        new_blob = ""
        status = "modified"
        for line in lines[1:]:
            if line.startswith("new file mode "):
                status = "added"
            elif line.startswith("deleted file mode "):
                status = "deleted"
            elif line.startswith("rename from "):
                rename_from = line.removeprefix("rename from ")
                status = "renamed"
            elif line.startswith("rename to "):
                rename_to = line.removeprefix("rename to ")
                status = "renamed"
            elif line.startswith("copy to "):
                copied_to = line.removeprefix("copy to ")
                status = "copied"
            elif match := INDEX_BLOBS.match(line):
                old_blob, new_blob = match.groups()

        path = rename_to or copied_to or (old_path if status == "deleted" else new_path)
        if not path:
            continue
        additions = sum(
            1 for line in lines[1:]
            if line.startswith("+") and not line.startswith("+++")
        )
        deletions = sum(
            1 for line in lines[1:]
            if line.startswith("-") and not line.startswith("---")
        )
        generated, generated_reason = classify_generated_file(path, block)
        item = {
            "path": path,
            "status": status,
            "additions": additions,
            "deletions": deletions,
            "patch": block.rstrip() + "\n",
            "binary": "GIT binary patch" in block or "Binary files " in block,
            "generated": generated,
            "url": github_diff_url(pr_url, path),
        }
        if generated_reason:
            item["generatedReason"] = generated_reason
        previous_path = rename_from or (old_path if old_path != path else "")
        if previous_path:
            item["previousPath"] = previous_path
        if (
            repo_root is not None
            and not item["binary"]
            and status in {"modified", "renamed", "copied"}
            and old_blob
            and new_blob
        ):
            old_contents = read_git_blob(repo_root, old_blob, blob_cache)
            new_contents = read_git_blob(repo_root, new_blob, blob_cache)
            if old_contents is not None and new_contents is not None:
                context_bytes = len(old_contents.encode("utf-8")) + len(
                    new_contents.encode("utf-8")
                )
                if embedded_context_bytes + context_bytes <= MAX_EMBEDDED_CONTEXT_BYTES:
                    item["oldContents"] = old_contents
                    item["newContents"] = new_contents
                    embedded_context_bytes += context_bytes
        files.append(item)
    return files


def fallback_review_groups(meta: dict[str, str], diff_files: list[dict]) -> list[dict]:
    return [
        {
            "id": "review-path",
            "title": "Review path",
            "objective": meta["summary"],
            "summary": meta["summary"],
            "details": [],
            "files": [
                {
                    "path": file["path"],
                    "url": file["url"],
                    "note": "Changed file in this pull request.",
                }
                for file in diff_files
            ],
            "comments": [],
            "links": [],
        }
    ]


def validate_review_groups(
    groups: list[dict],
    diff_files: list[dict],
    *,
    require_file_coverage: bool,
) -> None:
    diff_by_path = {file["path"]: file for file in diff_files}
    group_ids = [group["id"] for group in groups]
    if len(set(group_ids)) != len(group_ids):
        raise CompileError("Review guide has duplicate group IDs")

    referenced_files: list[str] = []
    for group in groups:
        group_file_paths = [file["path"] for file in group["files"]]
        if len(set(group_file_paths)) != len(group_file_paths):
            raise CompileError(f"review group {group['id']} repeats a changed file")
        for file in group["files"]:
            path = file["path"]
            if path not in diff_by_path:
                raise CompileError(f"review group {group['id']} references a file missing from the patch: {path}")
            file.setdefault("url", diff_by_path[path]["url"])
            referenced_files.append(path)

    if require_file_coverage and diff_files:
        duplicate_files = sorted({path for path in referenced_files if referenced_files.count(path) > 1})
        if duplicate_files:
            raise CompileError(
                "Review guide assigns changed files to more than one group: " + ", ".join(duplicate_files)
            )
        missing_files = sorted(set(diff_by_path) - set(referenced_files))
        if missing_files:
            raise CompileError("Review guide does not assign every changed file: " + ", ".join(missing_files))


def compile_walkthrough_dir(
    root: Path,
    patch: str = "",
    repo_root: Path | None = None,
) -> dict:
    manifest_path = root / "index.mdx"
    if not manifest_path.is_file():
        raise CompileError("walkthrough directory must contain index.mdx")

    for source_path in sorted(root.rglob("*.mdx")):
        reject_legacy_lens_syntax(
            source_path.read_text(encoding="utf-8"),
            str(source_path.relative_to(root)),
        )

    manifest = manifest_path.read_text(encoding="utf-8")
    lines = manifest.splitlines()
    meta, body_start = parse_frontmatter(lines)
    body = lines[body_start:]
    if not any(line.strip() == "# Review guide" for line in body):
        raise CompileError("index.mdx must contain # Review guide")

    references: list[tuple[str, str]] = []
    for line in body:
        if not line.strip():
            continue
        match = SECTION_REFERENCE.match(line.strip())
        if match:
            references.append(match.groups())

    if not references:
        raise CompileError("index.mdx must reference at least one Section MDX file")

    paths = [path for _, path in references]
    if len(set(paths)) != len(paths):
        raise CompileError("index.mdx repeats an MDX file reference")

    review_groups: list[dict] = []
    for label, relative_path in references:
        source = read_relative_mdx(root, relative_path, f"Section {label}")
        title, section_lines = parse_single_heading(source, f"Section {relative_path}")
        if title != label:
            raise CompileError(f"Section label {label} must match its heading {title}")
        review_groups.append(
            parse_review_group_with_guide(
                title,
                section_lines,
                f"Section {relative_path}",
            )
        )

    diff_files = parse_patch(patch, meta["prUrl"], repo_root)
    validate_review_groups(
        review_groups,
        diff_files,
        require_file_coverage=True,
    )
    for group in review_groups:
        guide_lines = group.pop("_guideLines")
        try:
            group["guide"] = compile_guide(
                guide_lines,
                group_id=group["id"],
                group_paths={file["path"] for file in group["files"]},
                diff_files=diff_files,
                patch=patch,
            )
        except GuideCompileError as error:
            raise CompileError(str(error)) from error
    return {
        "meta": {
            "title": meta["title"],
            "prUrl": meta["prUrl"],
            "baseRef": meta["baseRef"],
            "headRef": meta["headRef"],
            "headSha": meta["headSha"],
            "summary": meta["summary"],
        },
        "reviewGroups": review_groups,
        "diffFiles": diff_files,
    }


def compile_mdx(
    source: str,
    patch: str = "",
    repo_root: Path | None = None,
) -> dict:
    reject_legacy_lens_syntax(source, "page.mdx")
    lines = source.splitlines()
    meta, body_start = parse_frontmatter(lines)
    required_markers = (
        "import { WalkthroughApp }",
        "import { WalkthroughSource }",
        "<WalkthroughApp",
        "<WalkthroughSource>",
        "</WalkthroughSource>",
    )
    missing_markers = [marker for marker in required_markers if marker not in source]
    if missing_markers:
        raise CompileError(
            "page.mdx must import and render WalkthroughApp and wrap its source in WalkthroughSource; "
            "missing " + ", ".join(missing_markers)
        )

    sections: dict[str, list[str]] = {}
    current_label: str | None = None
    for line in lines[body_start:]:
        if line.strip() == "</WalkthroughSource>":
            current_label = None
            continue
        heading = FIRST_LEVEL_HEADING.match(line)
        if heading:
            label = heading.group(1)
            if label == REVIEW_GUIDE_LABEL:
                if label in sections:
                    raise CompileError(f"page.mdx repeats the {label} heading")
                current_label = label
                sections[current_label] = []
            else:
                current_label = None
            continue
        if current_label:
            sections[current_label].append(line)

    diff_files = parse_patch(patch, meta["prUrl"], repo_root)
    authored_review_guide = REVIEW_GUIDE_LABEL in sections
    review_groups = (
        parse_review_guide(sections[REVIEW_GUIDE_LABEL])
        if authored_review_guide
        else fallback_review_groups(meta, diff_files)
    )
    validate_review_groups(
        review_groups,
        diff_files,
        require_file_coverage=authored_review_guide,
    )
    result = {
        "meta": {
            "title": meta["title"],
            "prUrl": meta["prUrl"],
            "baseRef": meta["baseRef"],
            "headRef": meta["headRef"],
            "headSha": meta["headSha"],
            "summary": meta["summary"],
        },
        "reviewGroups": review_groups,
        "diffFiles": diff_files,
    }
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("src/content/walkthrough"))
    parser.add_argument("--output", type=Path, default=Path("src/data/walkthrough.generated.json"))
    parser.add_argument("--diff", type=Path, default=Path("src/data/walkthrough.patch"))
    parser.add_argument(
        "--include-full-context",
        action="store_true",
        help="Embed exact old/new Git blobs for native hunk expansion (localhost-only artifacts).",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        help="Repository used to resolve patch blob IDs (defaults to the current repository).",
    )
    args = parser.parse_args()

    try:
        patch = args.diff.read_text(encoding="utf-8") if args.diff.is_file() else ""
        site_root = Path(__file__).resolve().parent.parent
        marker_path = site_root / "src" / "data" / FULL_CONTEXT_MARKER_NAME
        include_full_context = args.include_full_context or marker_path.is_file()
        repo_root = None
        if include_full_context:
            repo_root = find_git_root(args.repo or Path.cwd())
            if repo_root is None:
                raise CompileError(
                    "full context was requested, but no Git repository could be resolved"
                )
        if args.input.is_dir():
            data = compile_walkthrough_dir(args.input, patch, repo_root)
        else:
            data = compile_mdx(
                args.input.read_text(encoding="utf-8"),
                patch,
                repo_root,
            )
    except (CompileError, OSError) as error:
        raise SystemExit(f"walkthrough compile failed: {error}") from error
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
