import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Diagnostic } from "./check.js";
import { compatibility } from "./compatibility-contract.js";
import {
  derivePluginId,
  fileSha256,
  type PluginManifest,
} from "./project.js";

export { compatibility };

export interface CompatibilityContract {
  readonly bbCliVersion: string;
  readonly engines: {
    readonly bb: string;
    readonly bbPluginSdk: string;
  };
  readonly pluginSdk: {
    readonly version: string;
    readonly major: number;
    readonly artifactFormatVersion: number;
  };
  readonly declarations: {
    readonly server: { readonly path: string; readonly sha256: string };
    readonly app: { readonly path: string; readonly sha256: string };
  };
  readonly hostShims: {
    readonly server: readonly string[];
    readonly frontend: readonly string[];
  };
  readonly registryUrl: string;
}

function diagnostic(
  code: string,
  message: string,
  hint: string,
  file: string,
): Diagnostic {
  return { code, severity: "error", message, hint, file };
}

export function checkSdkDeclarations(
  root: string,
  manifest: PluginManifest,
  contract: CompatibilityContract = compatibility,
): Diagnostic[] {
  const declarations = [
    contract.declarations.server,
    ...(manifest.bb?.app ? [contract.declarations.app] : []),
  ];
  const diagnostics: Diagnostic[] = [];
  for (const declaration of declarations) {
    const path = join(root, declaration.path);
    if (!existsSync(path)) {
      diagnostics.push(diagnostic(
        "BBK011",
        `canonical SDK declaration "${declaration.path}" is missing`,
        `Generate declarations with bb ${contract.bbCliVersion}; do not copy them from another release.`,
        declaration.path,
      ));
      continue;
    }
    const actual = fileSha256(path);
    if (actual !== declaration.sha256) {
      diagnostics.push(diagnostic(
        "BBK011",
        `SDK declaration "${declaration.path}" has SHA-256 ${actual}, expected ${declaration.sha256}`,
        `Restore the declaration generated by bb ${contract.bbCliVersion}.`,
        declaration.path,
      ));
    }
  }
  return diagnostics;
}

function readMetadata(path: string): Record<string, unknown> | null {
  try {
    const value = JSON.parse(readFileSync(path, "utf8")) as unknown;
    return typeof value === "object" && value !== null
      ? value as Record<string, unknown>
      : null;
  } catch {
    return null;
  }
}

export function checkBuildMetadata(
  root: string,
  manifest: PluginManifest,
  contract: CompatibilityContract = compatibility,
): Diagnostic[] {
  const pluginId = derivePluginId(manifest.name);
  const pluginVersion = manifest.version ?? "0.0.0";
  const files = [
    "dist/server.meta.json",
    ...(manifest.bb?.app ? ["dist/app.meta.json"] : []),
  ];
  const expected: Readonly<Record<string, unknown>> = {
    sdkMajor: contract.pluginSdk.major,
    sdkVersion: contract.pluginSdk.version,
    artifactFormatVersion: contract.pluginSdk.artifactFormatVersion,
    pluginId,
    pluginVersion,
    "builtWith.bbVersion": contract.bbCliVersion,
    "builtWith.pluginSdkVersion": contract.pluginSdk.version,
  };
  const diagnostics: Diagnostic[] = [];
  for (const file of files) {
    const metadata = readMetadata(join(root, file));
    if (!metadata) {
      diagnostics.push(diagnostic(
        "BBK013",
        `build metadata "${file}" is missing or invalid JSON`,
        `Build with bb ${contract.bbCliVersion}.`,
        file,
      ));
      continue;
    }
    const builtWith = typeof metadata.builtWith === "object" && metadata.builtWith !== null
      ? metadata.builtWith as Record<string, unknown>
      : {};
    for (const [field, wanted] of Object.entries(expected)) {
      const actual = field.startsWith("builtWith.")
        ? builtWith[field.slice("builtWith.".length)]
        : metadata[field];
      if (actual !== wanted) {
        diagnostics.push(diagnostic(
          "BBK013",
          `${file} field ${field} is ${JSON.stringify(actual)}, expected ${JSON.stringify(wanted)}`,
          `Rebuild with bb ${contract.bbCliVersion}; do not edit metadata by hand.`,
          file,
        ));
      }
    }
  }
  return diagnostics;
}

export const exactHostShims = new Set<string>([
  ...compatibility.hostShims.server,
  ...compatibility.hostShims.frontend,
]);

export const shimmedPackageRoots = new Set<string>(
  [...exactHostShims].map((specifier) => {
    if (!specifier.startsWith("@")) return specifier.split("/")[0] as string;
    return specifier.split("/").slice(0, 2).join("/");
  }),
);

export function isCompatibleHostVersion(version: string): boolean {
  const [major, minor] = compatibility.bbCliVersion.split(".");
  return new RegExp(`^${major}\\.${minor}\\.\\d+$`).test(version);
}
