// Generated by `bb-kit compatibility upgrade`. Do not edit by hand.
export const compatibility = {
  "bbCliVersion": "0.39.0",
  "engines": {
    "bb": ">=0.39.0 <1.0.0",
    "bbPluginSdk": ">=0.4.8"
  },
  "pluginSdk": {
    "version": "0.4.8",
    "major": 0,
    "artifactFormatVersion": 1
  },
  "sdkPackage": {
    "name": "@get-bb/plugin-sdk",
    "version": "0.4.8"
  },
  "hostShims": {
    "server": [
      "@get-bb/plugin-sdk"
    ],
    "frontend": [
      "@get-bb/plugin-sdk/app",
      "react",
      "react-dom",
      "react-dom/client",
      "react/jsx-runtime",
      "react/jsx-dev-runtime",
      "@bb/plugin-sdk/app",
      "@pierre/diffs",
      "@pierre/diffs/react",
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-context-menu",
      "@radix-ui/react-dialog",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-hover-card",
      "@radix-ui/react-menubar",
      "@radix-ui/react-navigation-menu",
      "@radix-ui/react-popover",
      "@radix-ui/react-select",
      "@radix-ui/react-tooltip",
      "sonner",
      "vaul"
    ]
  },
  "registryUrl": "https://raw.githubusercontent.com/get-bb/bb/desktop-v0.39.0/packages/plugin-registry/r/{name}.json"
} as const;
