// Generated by `bb-kit compatibility upgrade`. Do not edit by hand.
export const compatibility = {
  "bbCliVersion": "0.37.0",
  "engines": {
    "bb": ">=0.37.0 <0.38.0",
    "bbPluginSdk": "^0.4.1"
  },
  "pluginSdk": {
    "version": "0.4.1",
    "major": 0,
    "artifactFormatVersion": 1
  },
  "declarations": {
    "server": {
      "path": "types/bb-plugin-sdk.d.ts",
      "sha256": "92ed82ff874280ab0c239e11669da3ed040b800aa1e8dd59cdf9c617dafcaccb"
    },
    "app": {
      "path": "types/bb-plugin-sdk-app.d.ts",
      "sha256": "984e0539c6926d42ddaf666c6b6890a567d08f711d9ae73a9b986620230eed9a"
    }
  },
  "hostShims": {
    "server": [
      "@bb/plugin-sdk"
    ],
    "frontend": [
      "@bb/plugin-sdk/app",
      "react",
      "react-dom",
      "react-dom/client",
      "react/jsx-runtime",
      "react/jsx-dev-runtime",
      "@pierre/diffs",
      "@pierre/diffs/react",
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-context-menu",
      "@radix-ui/react-dialog",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-hover-card",
      "@radix-ui/react-menubar",
      "@radix-ui/react-navigation-menu",
      "@radix-ui/react-popover",
      "@radix-ui/react-select",
      "@radix-ui/react-tooltip",
      "sonner",
      "vaul"
    ]
  },
  "registryUrl": "https://raw.githubusercontent.com/get-bb/bb/desktop-v0.37.0/packages/plugin-registry/r/{name}.json"
} as const;
