import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const source = resolve(
  import.meta.dir,
  "../../../node_modules/nanocodex/pkg-web/nanocodex_bg.wasm",
);
const destination = resolve(import.meta.dir, "../host/generated/nanocodex-wasm.ts");
const bytes = await readFile(source);
const sha256 = createHash("sha256").update(bytes).digest("hex");
await mkdir(dirname(destination), { recursive: true });
await writeFile(
  destination,
  [
    "// Generated by scripts/generate-wasm-source.ts. Do not edit.",
    `export const NANOCODEX_WASM_SHA256 = ${JSON.stringify(sha256)};`,
    `export const NANOCODEX_WASM_BASE64 = ${JSON.stringify(bytes.toString("base64"))};`,
    "",
  ].join("\n"),
  { mode: 0o644 },
);
