import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const generatedDirectory = resolve(import.meta.dir, "../host/generated");
const wasmSource = resolve(
  import.meta.dir,
  "../../../node_modules/nanocodex/pkg-web/nanocodex_bg.wasm",
);
const runtimeEntry = resolve(import.meta.dir, "nanocodex-runtime-entry.ts");

await mkdir(generatedDirectory, { recursive: true });

const bytes = await readFile(wasmSource);
const sha256 = createHash("sha256").update(bytes).digest("hex");
await writeFile(
  resolve(generatedDirectory, "nanocodex-wasm.ts"),
  [
    "// Generated by scripts/generate-binding.ts. Do not edit.",
    `export const NANOCODEX_WASM_SHA256 = ${JSON.stringify(sha256)};`,
    `export const NANOCODEX_WASM_BASE64 = ${JSON.stringify(bytes.toString("base64"))};`,
    "",
  ].join("\n"),
  { mode: 0o644 },
);

const runtime = await Bun.build({
  entrypoints: [runtimeEntry],
  format: "esm",
  minify: true,
  packages: "bundle",
  sourcemap: "none",
  target: "node",
});
if (!runtime.success) {
  throw new AggregateError(runtime.logs, "Could not embed the NanoCodex JavaScript runtime");
}
const output = runtime.outputs[0];
if (output === undefined) throw new Error("The NanoCodex runtime build produced no output");
await writeFile(
  resolve(generatedDirectory, "nanocodex-runtime.mjs"),
  `// Generated by scripts/generate-binding.ts. Do not edit.\n${await output.text()}`,
  { mode: 0o644 },
);
await writeFile(
  resolve(generatedDirectory, "nanocodex-runtime.d.mts"),
  [
    "// Generated by scripts/generate-binding.ts. Do not edit.",
    'export { Agent } from "nanocodex/node";',
    'export { chatGpt } from "nanocodex/node/transport";',
    'export { ChatGptSubscription } from "nanocodex/worker";',
    "",
  ].join("\n"),
  { mode: 0o644 },
);
